module platform {
    export class TypeSubDjs {
        public static AIWEIYOU: string = "aiweiyou";//爱微游
        public static HORTOR: string = "hortor";//疯狂游乐场
        public static QIANBAO: string = "qianbao";//钱宝
        public static KUGOU: string = "kugou";//酷狗
        public static UNKNOWN: string = "unknown";//通用
        public static QIDIAN: string = "qidian";//起点
        public static CCYOU: string = "ccyou";//虫虫游
        public static QUNHEI: string = "qunhei";//群黑
        public static MEITU: string = "meitu";//美图
        public static KONGZHONG: string = "kongzhong";//空中网
        public static BAISI: string = "baisi";//百思
        public static FANQIE: string = "fanqie";//番茄
        public static CHUANGDU: string = "changdu";//畅读书城
        public static CHANGXIANG: string = "changxiang";//畅想
        public static WANBA: string = "wanba";//玩吧
        public static IQIYI: string = "iqiyi";//爱奇艺
        public static HUOXINGWAN: string = "huoxingwan";//火星玩
        public static YOUKU: string = "youku";//游酷
        public static YOUZU: string = "youzu";//游族
        public static TEST: string = "test";//测试渠道
        public static GUOPAN: string = "guopan";//果盘
        public static XINGYOU: string = "xinyou";//新游
        public static SINA: string = "sina";//新浪
        public static SOUGOU: string = "sougou";//搜狗
        public static ZHIWU: string = "zhiwu";//指舞飞游
        public static GUAIMAO: string = "guaimao";//怪猫
        public static WEIBO: string = "weibo";//微博
        public static DANGLE: string = "dangle";//当乐
        public static ALIPAY: string = "alipay";//支付包
        public static SHUNWANG: string = "shunwang";//顺网
        public static SHOUQIANBA: string = "shouqianba";//收钱吧
        public static XIAOMI: string = "xiaomi";//小米

        public static YYB: string = "yyb";//应用宝
        public static XIAOXIONG: string = "xiaoxiong";//小熊游乐场
        public static ANZHI: string = "anzhi";//安智
        public static QIQU: string = "qiqu";//奇趣
        public static TANWAN: string = "tianwan";//天玩
        public static TIANTUAN: string = "tiantuan";//天团
        public static HIWANWAN: string = "hiwanwan";//嗨玩玩
        public static TONGBUTUI: string = "tongbutui";//同步推
        public static KOUDAI: string = "koudai";//口袋微游戏
        public static BINGQU: string = "bingqu";//冰趣
        public static YOUSENG: string = "youseng";//优森移动
        public static LEGUYU: string = "leguyu";//乐谷鱼
        public static WANNENG: string = "wanneng";//万能wifi
        public static YHD: string = "yhd";//一号店
        public static AIAIYOU: string = "aiaiyou";//爱爱游
        public static QQREAD: string = "qqread";//QQ阅读
        public static QQBROWSER: string = "qqbrowser ";//QQ浏览器
        public static QQGAME: string = "qqgame";//QQ大厅
        public static HENKKUAI: string = "henkuai";//9G(很快)
        public static G9G: string = "9g";//9G
        public static G7K7K: string = "7k7k";//7k7k
        public static G7724: string = "7724";//7724
        public static G68V: string = "68v";//68微游戏
        public static G59YOU: string = "59you";//59游
        public static G5543: string = "5543";//5543
        public static G4399: string = "4399";//4399
        public static G360: string = "360";//360
        public static G1758: string = "1758";//1758
        public static FENGWAN: string = "fengwan";//疯玩
        public static KUPAI: string = "kupai";//酷派
        public static SOUGOUZB: string = "sougouzb";//搜狗直播
    }
}